create extension if not exists pgcrypto;

create table if not exists public.pacientes (
  id bigint generated by default as identity primary key,
  nombre text not null,
  apellidos text,
  edad integer,
  sexo text default 'femenino',
  fecha_nac date,
  telefono text,
  email text,
  objetivo text,
  discapacidad text,
  notas text,
  motivo_consulta text,
  antecedentes_personales text,
  antecedentes_familiares text,
  medicamentos text,
  alergias text,
  suplementacion text,
  actividad_fisica_base text,
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.deporte_adaptado_pacientes (
  id bigint generated by default as identity primary key,
  nombre text not null,
  apellidos text,
  edad integer,
  sexo text default 'femenino',
  fecha_nac date,
  telefono text,
  email text,
  objetivo text,
  notas text,
  motivo_consulta text,
  antecedentes_personales text,
  antecedentes_familiares text,
  medicamentos text,
  alergias text,
  suplementacion text,
  actividad_fisica_base text,
  created_at timestamptz not null default now()
);

create table if not exists public.consultas (
  id bigint generated by default as identity primary key,
  paciente_id bigint not null references public.pacientes(id) on delete cascade,
  fecha date not null,
  hora time,
  tipo_cita text default 'seguimiento',
  motivo text,
  peso numeric(6,2),
  talla numeric(6,2),
  imc numeric(6,2),
  cintura numeric(6,2),
  cadera numeric(6,2),
  icc numeric(6,2),
  brazo numeric(6,2),
  circunferencia_brazo_relajado numeric(6,2),
  circunferencia_brazo_flexionado numeric(6,2),
  circunferencia_muslo numeric(6,2),
  circunferencia_pantorrilla numeric(6,2),
  perimetro_torax numeric(6,2),
  perimetro_muslo numeric(6,2),
  perimetro_pantorrilla numeric(6,2),
  diametro_humero numeric(6,2),
  diametro_biestiloideo numeric(6,2),
  diametro_rodilla numeric(6,2),
  pliegue_triceps numeric(6,2),
  pliegue_biceps numeric(6,2),
  pliegue_subescapular numeric(6,2),
  pliegue_cresta_iliaca numeric(6,2),
  pliegue_supraespinal numeric(6,2),
  pliegue_abdominal numeric(6,2),
  pliegue_muslo numeric(6,2),
  pliegue_pantorrilla numeric(6,2),
  yuhasz_grasa_pct numeric(6,2),
  yuhasz_grasa_kg numeric(6,2),
  yuhasz_libre_grasa_pct numeric(6,2),
  yuhasz_libre_grasa_kg numeric(6,2),
  peterson_grasa_pct numeric(6,2),
  peterson_grasa_kg numeric(6,2),
  evans_grasa_pct numeric(6,2),
  evans_grasa_kg numeric(6,2),
  von_dobeln_osea_kg numeric(6,2),
  wurch_residual_kg numeric(6,2),
  muscular_derivada_kg numeric(6,2),
  muscular_derivada_pct numeric(6,2),
  matiegka_muscular_kg numeric(6,2),
  matiegka_muscular_pct numeric(6,2),
  antrop_obs text,
  glucosa numeric(8,2),
  hba1c numeric(5,2),
  colesterol_total numeric(8,2),
  trigliceridos numeric(8,2),
  hdl numeric(8,2),
  ldl numeric(8,2),
  vit_d numeric(8,2),
  ferritina numeric(8,2),
  bio_obs text,
  adherencia text default 'buena',
  recordatorio_24h text,
  desayuno_24h text,
  colacion_am_24h text,
  comida_24h text,
  colacion_pm_24h text,
  cena_24h text,
  bebidas_24h text,
  observaciones_24h text,
  hambre integer,
  saciedad integer,
  hidratacion integer,
  dieta_obs text,
  diagnostico_nutricional text,
  adime_valoracion text,
  adime_diagnostico text,
  adime_intervencion text,
  adime_monitoreo text,
  objetivos text,
  indicaciones text,
  proxima_cita date,
  estado text default 'completada',
  created_at timestamptz not null default now()
);

create table if not exists public.paciente_plan_alimentos (
  id bigint generated by default as identity primary key,
  paciente_id bigint not null references public.pacientes(id) on delete cascade,
  consulta_id bigint references public.consultas(id) on delete set null,
  alimento_nombre text not null,
  grupo text,
  porcion text,
  intercambio text,
  tiempo_comida text not null default 'sin_asignar',
  receta text,
  sustituciones text[],
  orden integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.alimentos_personalizados (
  id bigint generated by default as identity primary key,
  name text not null,
  grupo text not null,
  porcion text,
  intercambio text,
  kcal numeric(8,2) not null default 0,
  prot numeric(8,2) not null default 0,
  carbs numeric(8,2) not null default 0,
  fat numeric(8,2) not null default 0,
  tags text[],
  tiempos text[],
  created_at timestamptz not null default now()
);

create table if not exists public.smae_alimentos (
  id bigint generated by default as identity primary key,
  name text not null,
  grupo text not null,
  porcion text,
  intercambio text,
  kcal numeric(8,2) not null default 0,
  prot numeric(8,2) not null default 0,
  carbs numeric(8,2) not null default 0,
  fat numeric(8,2) not null default 0,
  tags text[],
  tiempos text[],
  created_at timestamptz not null default now()
);

create table if not exists public.paciente_plan_semanal (
  id bigint generated by default as identity primary key,
  paciente_id bigint not null references public.pacientes(id) on delete cascade,
  dia_semana text not null,
  tiempo_comida text not null,
  preparacion text,
  created_at timestamptz not null default now()
);

create table if not exists public.platillos_inteligentes (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  meal_type text,
  dish_type text,
  cuisine_type text,
  protein numeric(8,2) not null default 0,
  carbs numeric(8,2) not null default 0,
  fat numeric(8,2) not null default 0,
  kcal numeric(8,2) not null default 0,
  tags text,
  health_labels text[],
  diet_labels text[],
  allergen_labels text[],
  image_url text,
  yield numeric(6,2),
  ingredients jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.recetas_estructuradas (
  id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text,
  categoria text not null default 'comida',
  meal_type text,
  dish_type text,
  cuisine_type text,
  objetivos text[],
  condiciones_compatibles text[],
  health_labels text[],
  diet_labels text[],
  allergen_labels text[],
  difficulty text,
  tiempo_prep integer,
  porciones numeric(6,2) default 1,
  yield numeric(6,2) default 1,
  ingredientes jsonb not null default '[]'::jsonb,
  pasos text[] not null default '{}'::text[],
  sustituciones jsonb not null default '[]'::jsonb,
  tags text[],
  macros jsonb not null default '{}'::jsonb,
  micros jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.plantillas_clinicas (
  id bigint generated by default as identity primary key,
  nombre text not null,
  perfil text not null default 'general',
  descripcion text,
  week_assignments jsonb not null default '{}'::jsonb,
  recommended_recipe_uids text[],
  allowed_tags text[],
  blocked_allergens text[],
  created_at timestamptz not null default now()
);

create table if not exists public.paciente_recetas_favoritas (
  id bigint generated by default as identity primary key,
  paciente_id bigint not null references public.pacientes(id) on delete cascade,
  recipe_uid text not null,
  recipe_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.paciente_plan_adherencia (
  id bigint generated by default as identity primary key,
  paciente_id bigint not null references public.pacientes(id) on delete cascade,
  fecha date not null,
  dia_semana text not null,
  tiempo_comida text not null,
  estado text not null default 'pendiente',
  recipe_uid text,
  recipe_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.paciente_calculo_dietetico (
  id bigint generated by default as identity primary key,
  paciente_id bigint not null references public.pacientes(id) on delete cascade,
  consulta_id bigint references public.consultas(id) on delete set null,
  formula_referencia text not null default 'mifflin',
  factor_actividad numeric(6,3) not null default 1.55,
  perfil_clinico text,
  objetivo text,
  peso_actual numeric(6,2),
  talla numeric(6,2),
  edad integer,
  sexo text,
  peso_ideal numeric(6,2),
  peso_ajustado numeric(6,2),
  geb_harris_benedict numeric(8,2),
  get_harris_benedict numeric(8,2),
  geb_mifflin_st_jeor numeric(8,2),
  get_mifflin_st_jeor numeric(8,2),
  geb_katch_mcardle numeric(8,2),
  get_katch_mcardle numeric(8,2),
  geb_schofield numeric(8,2),
  get_schofield numeric(8,2),
  geb_oms_fao_unu numeric(8,2),
  get_oms_fao_unu numeric(8,2),
  kcal_objetivo numeric(8,2),
  proteina_g numeric(8,2),
  carbohidratos_g numeric(8,2),
  grasa_g numeric(8,2),
  proteina_pct numeric(6,2),
  carbohidratos_pct numeric(6,2),
  grasa_pct numeric(6,2),
  peso_base_macros numeric(6,2),
  nota_macros text,
  custom_body_rows jsonb,
  custom_nutrient_rows jsonb,
  custom_duration_rows jsonb,
  plan_scope text not null default 'semanal',
  created_at timestamptz not null default now()
);

create table if not exists public.paciente_checkins (
  id bigint generated by default as identity primary key,
  paciente_id bigint not null references public.pacientes(id) on delete cascade,
  fecha date not null,
  energia integer not null default 3,
  sueno integer not null default 3,
  digestion integer not null default 3,
  adherencia integer not null default 3,
  entrenamiento integer not null default 3,
  notas text,
  created_at timestamptz not null default now()
);

create table if not exists public.paciente_journal_entries (
  id bigint generated by default as identity primary key,
  paciente_id bigint not null references public.pacientes(id) on delete cascade,
  fecha date not null,
  hambre integer not null default 3,
  saciedad integer not null default 3,
  sintomas text,
  sueno_horas numeric(4,1),
  entrenamiento text,
  adherencia integer not null default 3,
  agua_litros numeric(4,1),
  notas text,
  created_at timestamptz not null default now()
);

create table if not exists public.agenda_recordatorios (
  id bigint generated by default as identity primary key,
  paciente_id bigint not null references public.pacientes(id) on delete cascade,
  titulo text not null,
  fecha date not null,
  hora time,
  tipo text not null default 'consulta',
  canal text not null default 'interno',
  estado_envio text not null default 'no_aplica',
  nota text,
  completado boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists consultas_paciente_id_idx on public.consultas (paciente_id);
create index if not exists deporte_adaptado_pacientes_nombre_idx on public.deporte_adaptado_pacientes (nombre);
create index if not exists consultas_fecha_idx on public.consultas (fecha);
create index if not exists paciente_plan_alimentos_paciente_id_idx on public.paciente_plan_alimentos (paciente_id);
create index if not exists alimentos_personalizados_created_at_idx on public.alimentos_personalizados (created_at);
create index if not exists smae_alimentos_name_idx on public.smae_alimentos (name);
create index if not exists paciente_plan_semanal_paciente_id_idx on public.paciente_plan_semanal (paciente_id);
create index if not exists platillos_inteligentes_category_idx on public.platillos_inteligentes (category);
create index if not exists platillos_inteligentes_meal_type_idx on public.platillos_inteligentes (meal_type);
create index if not exists platillos_inteligentes_dish_type_idx on public.platillos_inteligentes (dish_type);
create index if not exists recetas_estructuradas_categoria_idx on public.recetas_estructuradas (categoria);
create index if not exists recetas_estructuradas_meal_type_idx on public.recetas_estructuradas (meal_type);
create index if not exists plantillas_clinicas_perfil_idx on public.plantillas_clinicas (perfil);
create index if not exists paciente_recetas_favoritas_paciente_id_idx on public.paciente_recetas_favoritas (paciente_id);
create index if not exists paciente_plan_adherencia_paciente_id_idx on public.paciente_plan_adherencia (paciente_id);
create index if not exists paciente_calculo_dietetico_paciente_id_idx on public.paciente_calculo_dietetico (paciente_id);
create index if not exists paciente_checkins_paciente_id_idx on public.paciente_checkins (paciente_id);
create index if not exists paciente_journal_entries_paciente_id_idx on public.paciente_journal_entries (paciente_id);
create index if not exists agenda_recordatorios_paciente_id_idx on public.agenda_recordatorios (paciente_id);
create unique index if not exists paciente_plan_semanal_unique_idx on public.paciente_plan_semanal (paciente_id, dia_semana, tiempo_comida);
create unique index if not exists platillos_inteligentes_name_unique_idx on public.platillos_inteligentes (name);
create unique index if not exists paciente_recetas_favoritas_unique_idx on public.paciente_recetas_favoritas (paciente_id, recipe_uid);
create unique index if not exists paciente_plan_adherencia_unique_idx on public.paciente_plan_adherencia (paciente_id, fecha, tiempo_comida);

alter table public.consultas add column if not exists pliegue_triceps numeric(6,2);
alter table public.consultas add column if not exists pliegue_biceps numeric(6,2);
alter table public.consultas add column if not exists pliegue_subescapular numeric(6,2);
alter table public.consultas add column if not exists pliegue_cresta_iliaca numeric(6,2);
alter table public.consultas add column if not exists pliegue_supraespinal numeric(6,2);
alter table public.consultas add column if not exists pliegue_abdominal numeric(6,2);
alter table public.consultas add column if not exists pliegue_muslo numeric(6,2);
alter table public.consultas add column if not exists pliegue_pantorrilla numeric(6,2);
alter table public.consultas add column if not exists circunferencia_brazo_relajado numeric(6,2);
alter table public.consultas add column if not exists circunferencia_brazo_flexionado numeric(6,2);
alter table public.consultas add column if not exists circunferencia_muslo numeric(6,2);
alter table public.platillos_inteligentes add column if not exists meal_type text;
alter table public.platillos_inteligentes add column if not exists dish_type text;
alter table public.platillos_inteligentes add column if not exists cuisine_type text;
alter table public.platillos_inteligentes add column if not exists health_labels text[];
alter table public.platillos_inteligentes add column if not exists diet_labels text[];
alter table public.platillos_inteligentes add column if not exists allergen_labels text[];
alter table public.platillos_inteligentes add column if not exists image_url text;
alter table public.platillos_inteligentes add column if not exists yield numeric(6,2);
alter table public.platillos_inteligentes add column if not exists ingredients jsonb;
alter table public.consultas add column if not exists circunferencia_pantorrilla numeric(6,2);
alter table public.consultas add column if not exists perimetro_torax numeric(6,2);
alter table public.consultas add column if not exists perimetro_muslo numeric(6,2);
alter table public.consultas add column if not exists perimetro_pantorrilla numeric(6,2);
alter table public.consultas add column if not exists diametro_humero numeric(6,2);
alter table public.consultas add column if not exists diametro_biestiloideo numeric(6,2);
alter table public.consultas add column if not exists diametro_rodilla numeric(6,2);
alter table public.consultas add column if not exists yuhasz_grasa_pct numeric(6,2);
alter table public.consultas add column if not exists yuhasz_grasa_kg numeric(6,2);
alter table public.consultas add column if not exists yuhasz_libre_grasa_pct numeric(6,2);
alter table public.consultas add column if not exists yuhasz_libre_grasa_kg numeric(6,2);
alter table public.consultas add column if not exists peterson_grasa_pct numeric(6,2);
alter table public.consultas add column if not exists peterson_grasa_kg numeric(6,2);
alter table public.consultas add column if not exists evans_grasa_pct numeric(6,2);
alter table public.consultas add column if not exists evans_grasa_kg numeric(6,2);
alter table public.consultas add column if not exists von_dobeln_osea_kg numeric(6,2);
alter table public.consultas add column if not exists wurch_residual_kg numeric(6,2);
alter table public.consultas add column if not exists muscular_derivada_kg numeric(6,2);
alter table public.consultas add column if not exists muscular_derivada_pct numeric(6,2);
alter table public.consultas add column if not exists matiegka_muscular_kg numeric(6,2);
alter table public.consultas add column if not exists matiegka_muscular_pct numeric(6,2);
alter table public.consultas add column if not exists adime_valoracion text;
alter table public.consultas add column if not exists adime_diagnostico text;
alter table public.consultas add column if not exists adime_intervencion text;
alter table public.consultas add column if not exists adime_monitoreo text;
alter table public.consultas add column if not exists desayuno_24h text;
alter table public.consultas add column if not exists colacion_am_24h text;
alter table public.consultas add column if not exists comida_24h text;
alter table public.consultas add column if not exists colacion_pm_24h text;
alter table public.consultas add column if not exists cena_24h text;
alter table public.consultas add column if not exists bebidas_24h text;
alter table public.consultas add column if not exists observaciones_24h text;
alter table public.pacientes add column if not exists motivo_consulta text;
alter table public.pacientes add column if not exists antecedentes_personales text;
alter table public.pacientes add column if not exists antecedentes_familiares text;
alter table public.pacientes add column if not exists medicamentos text;
alter table public.pacientes add column if not exists alergias text;
alter table public.pacientes add column if not exists suplementacion text;
alter table public.pacientes add column if not exists actividad_fisica_base text;
alter table public.deporte_adaptado_pacientes add column if not exists motivo_consulta text;
alter table public.deporte_adaptado_pacientes add column if not exists discapacidad text;
alter table public.deporte_adaptado_pacientes add column if not exists antecedentes_personales text;
alter table public.deporte_adaptado_pacientes add column if not exists antecedentes_familiares text;
alter table public.deporte_adaptado_pacientes add column if not exists medicamentos text;
alter table public.deporte_adaptado_pacientes add column if not exists alergias text;
alter table public.deporte_adaptado_pacientes add column if not exists suplementacion text;
alter table public.deporte_adaptado_pacientes add column if not exists actividad_fisica_base text;
alter table public.agenda_recordatorios add column if not exists canal text default 'interno';
alter table public.agenda_recordatorios add column if not exists estado_envio text default 'no_aplica';
alter table public.paciente_calculo_dietetico add column if not exists geb_katch_mcardle numeric(8,2);
alter table public.paciente_calculo_dietetico add column if not exists get_katch_mcardle numeric(8,2);
alter table public.paciente_calculo_dietetico add column if not exists custom_body_rows jsonb;
alter table public.paciente_calculo_dietetico add column if not exists custom_nutrient_rows jsonb;
alter table public.paciente_calculo_dietetico add column if not exists custom_duration_rows jsonb;
alter table public.paciente_calculo_dietetico add column if not exists plan_scope text not null default 'semanal';
alter table public.paciente_plan_semanal add column if not exists recipe_uid text;

alter table public.pacientes enable row level security;
alter table public.deporte_adaptado_pacientes enable row level security;
alter table public.consultas enable row level security;
alter table public.paciente_plan_alimentos enable row level security;
alter table public.alimentos_personalizados enable row level security;
alter table public.smae_alimentos enable row level security;
alter table public.paciente_plan_semanal enable row level security;
alter table public.platillos_inteligentes enable row level security;
alter table public.recetas_estructuradas enable row level security;
alter table public.plantillas_clinicas enable row level security;
alter table public.paciente_recetas_favoritas enable row level security;
alter table public.paciente_plan_adherencia enable row level security;
alter table public.paciente_calculo_dietetico enable row level security;
alter table public.paciente_checkins enable row level security;
alter table public.paciente_journal_entries enable row level security;
alter table public.agenda_recordatorios enable row level security;

drop policy if exists "anon_select_pacientes" on public.pacientes;
create policy "anon_select_pacientes"
on public.pacientes
for select
to anon
using (true);

drop policy if exists "anon_select_deporte_adaptado_pacientes" on public.deporte_adaptado_pacientes;
create policy "anon_select_deporte_adaptado_pacientes"
on public.deporte_adaptado_pacientes
for select
to anon
using (true);

drop policy if exists "anon_insert_pacientes" on public.pacientes;
create policy "anon_insert_pacientes"
on public.pacientes
for insert
to anon
with check (true);

drop policy if exists "anon_insert_deporte_adaptado_pacientes" on public.deporte_adaptado_pacientes;
create policy "anon_insert_deporte_adaptado_pacientes"
on public.deporte_adaptado_pacientes
for insert
to anon
with check (true);

drop policy if exists "anon_update_pacientes" on public.pacientes;
create policy "anon_update_pacientes"
on public.pacientes
for update
to anon
using (true)
with check (true);

drop policy if exists "anon_update_deporte_adaptado_pacientes" on public.deporte_adaptado_pacientes;
create policy "anon_update_deporte_adaptado_pacientes"
on public.deporte_adaptado_pacientes
for update
to anon
using (true)
with check (true);

drop policy if exists "anon_delete_deporte_adaptado_pacientes" on public.deporte_adaptado_pacientes;
create policy "anon_delete_deporte_adaptado_pacientes"
on public.deporte_adaptado_pacientes
for delete
to anon
using (true);

drop policy if exists "anon_select_consultas" on public.consultas;
create policy "anon_select_consultas"
on public.consultas
for select
to anon
using (true);

drop policy if exists "anon_insert_consultas" on public.consultas;
create policy "anon_insert_consultas"
on public.consultas
for insert
to anon
with check (true);

drop policy if exists "anon_update_consultas" on public.consultas;
create policy "anon_update_consultas"
on public.consultas
for update
to anon
using (true)
with check (true);

drop policy if exists "anon_select_plan_alimentos" on public.paciente_plan_alimentos;
create policy "anon_select_plan_alimentos"
on public.paciente_plan_alimentos
for select
to anon
using (true);

drop policy if exists "anon_insert_plan_alimentos" on public.paciente_plan_alimentos;
create policy "anon_insert_plan_alimentos"
on public.paciente_plan_alimentos
for insert
to anon
with check (true);

drop policy if exists "anon_update_plan_alimentos" on public.paciente_plan_alimentos;
create policy "anon_update_plan_alimentos"
on public.paciente_plan_alimentos
for update
to anon
using (true)
with check (true);

drop policy if exists "anon_delete_plan_alimentos" on public.paciente_plan_alimentos;
create policy "anon_delete_plan_alimentos"
on public.paciente_plan_alimentos
for delete
to anon
using (true);

drop policy if exists "anon_select_alimentos_personalizados" on public.alimentos_personalizados;
create policy "anon_select_alimentos_personalizados"
on public.alimentos_personalizados
for select
to anon
using (true);

drop policy if exists "anon_insert_alimentos_personalizados" on public.alimentos_personalizados;
create policy "anon_insert_alimentos_personalizados"
on public.alimentos_personalizados
for insert
to anon
with check (true);

drop policy if exists "anon_update_alimentos_personalizados" on public.alimentos_personalizados;
create policy "anon_update_alimentos_personalizados"
on public.alimentos_personalizados
for update
to anon
using (true)
with check (true);

drop policy if exists "anon_delete_alimentos_personalizados" on public.alimentos_personalizados;
create policy "anon_delete_alimentos_personalizados"
on public.alimentos_personalizados
for delete
to anon
using (true);

drop policy if exists "anon_select_smae_alimentos" on public.smae_alimentos;
create policy "anon_select_smae_alimentos"
on public.smae_alimentos
for select
to anon
using (true);

drop policy if exists "anon_insert_smae_alimentos" on public.smae_alimentos;
create policy "anon_insert_smae_alimentos"
on public.smae_alimentos
for insert
to anon
with check (true);

drop policy if exists "anon_update_smae_alimentos" on public.smae_alimentos;
create policy "anon_update_smae_alimentos"
on public.smae_alimentos
for update
to anon
using (true)
with check (true);

drop policy if exists "anon_delete_smae_alimentos" on public.smae_alimentos;
create policy "anon_delete_smae_alimentos"
on public.smae_alimentos
for delete
to anon
using (true);

drop policy if exists "anon_select_plan_semanal" on public.paciente_plan_semanal;
create policy "anon_select_plan_semanal"
on public.paciente_plan_semanal
for select
to anon
using (true);

drop policy if exists "anon_insert_plan_semanal" on public.paciente_plan_semanal;
create policy "anon_insert_plan_semanal"
on public.paciente_plan_semanal
for insert
to anon
with check (true);

drop policy if exists "anon_update_plan_semanal" on public.paciente_plan_semanal;
create policy "anon_update_plan_semanal"
on public.paciente_plan_semanal
for update
to anon
using (true)
with check (true);

drop policy if exists "anon_delete_plan_semanal" on public.paciente_plan_semanal;
create policy "anon_delete_plan_semanal"
on public.paciente_plan_semanal
for delete
to anon
using (true);

drop policy if exists "anon_select_journal_entries" on public.paciente_journal_entries;
create policy "anon_select_journal_entries"
on public.paciente_journal_entries
for select
to anon
using (true);

drop policy if exists "anon_insert_journal_entries" on public.paciente_journal_entries;
create policy "anon_insert_journal_entries"
on public.paciente_journal_entries
for insert
to anon
with check (true);

drop policy if exists "anon_update_journal_entries" on public.paciente_journal_entries;
create policy "anon_update_journal_entries"
on public.paciente_journal_entries
for update
to anon
using (true)
with check (true);

drop policy if exists "anon_delete_journal_entries" on public.paciente_journal_entries;
create policy "anon_delete_journal_entries"
on public.paciente_journal_entries
for delete
to anon
using (true);

drop policy if exists "anon_select_platillos_inteligentes" on public.platillos_inteligentes;
create policy "anon_select_platillos_inteligentes"
on public.platillos_inteligentes
for select
to anon
using (true);

drop policy if exists "anon_insert_platillos_inteligentes" on public.platillos_inteligentes;
create policy "anon_insert_platillos_inteligentes"
on public.platillos_inteligentes
for insert
to anon
with check (true);

drop policy if exists "anon_update_platillos_inteligentes" on public.platillos_inteligentes;
create policy "anon_update_platillos_inteligentes"
on public.platillos_inteligentes
for update
to anon
using (true)
with check (true);

drop policy if exists "anon_delete_platillos_inteligentes" on public.platillos_inteligentes;
create policy "anon_delete_platillos_inteligentes"
on public.platillos_inteligentes
for delete
to anon
using (true);

drop policy if exists "anon_select_recetas_estructuradas" on public.recetas_estructuradas;
create policy "anon_select_recetas_estructuradas"
on public.recetas_estructuradas
for select
to anon
using (true);

drop policy if exists "anon_insert_recetas_estructuradas" on public.recetas_estructuradas;
create policy "anon_insert_recetas_estructuradas"
on public.recetas_estructuradas
for insert
to anon
with check (true);

drop policy if exists "anon_update_recetas_estructuradas" on public.recetas_estructuradas;
create policy "anon_update_recetas_estructuradas"
on public.recetas_estructuradas
for update
to anon
using (true)
with check (true);

drop policy if exists "anon_delete_recetas_estructuradas" on public.recetas_estructuradas;
create policy "anon_delete_recetas_estructuradas"
on public.recetas_estructuradas
for delete
to anon
using (true);

drop policy if exists "anon_select_plantillas_clinicas" on public.plantillas_clinicas;
create policy "anon_select_plantillas_clinicas"
on public.plantillas_clinicas
for select
to anon
using (true);

drop policy if exists "anon_insert_plantillas_clinicas" on public.plantillas_clinicas;
create policy "anon_insert_plantillas_clinicas"
on public.plantillas_clinicas
for insert
to anon
with check (true);

drop policy if exists "anon_update_plantillas_clinicas" on public.plantillas_clinicas;
create policy "anon_update_plantillas_clinicas"
on public.plantillas_clinicas
for update
to anon
using (true)
with check (true);

drop policy if exists "anon_delete_plantillas_clinicas" on public.plantillas_clinicas;
create policy "anon_delete_plantillas_clinicas"
on public.plantillas_clinicas
for delete
to anon
using (true);

drop policy if exists "anon_select_recetas_favoritas" on public.paciente_recetas_favoritas;
create policy "anon_select_recetas_favoritas"
on public.paciente_recetas_favoritas
for select
to anon
using (true);

drop policy if exists "anon_insert_recetas_favoritas" on public.paciente_recetas_favoritas;
create policy "anon_insert_recetas_favoritas"
on public.paciente_recetas_favoritas
for insert
to anon
with check (true);

drop policy if exists "anon_update_recetas_favoritas" on public.paciente_recetas_favoritas;
create policy "anon_update_recetas_favoritas"
on public.paciente_recetas_favoritas
for update
to anon
using (true)
with check (true);

drop policy if exists "anon_delete_recetas_favoritas" on public.paciente_recetas_favoritas;
create policy "anon_delete_recetas_favoritas"
on public.paciente_recetas_favoritas
for delete
to anon
using (true);

drop policy if exists "anon_select_plan_adherencia" on public.paciente_plan_adherencia;
create policy "anon_select_plan_adherencia"
on public.paciente_plan_adherencia
for select
to anon
using (true);

drop policy if exists "anon_insert_plan_adherencia" on public.paciente_plan_adherencia;
create policy "anon_insert_plan_adherencia"
on public.paciente_plan_adherencia
for insert
to anon
with check (true);

drop policy if exists "anon_update_plan_adherencia" on public.paciente_plan_adherencia;
create policy "anon_update_plan_adherencia"
on public.paciente_plan_adherencia
for update
to anon
using (true)
with check (true);

drop policy if exists "anon_delete_plan_adherencia" on public.paciente_plan_adherencia;
create policy "anon_delete_plan_adherencia"
on public.paciente_plan_adherencia
for delete
to anon
using (true);

drop policy if exists "anon_select_calculo_dietetico" on public.paciente_calculo_dietetico;
create policy "anon_select_calculo_dietetico"
on public.paciente_calculo_dietetico
for select
to anon
using (true);

drop policy if exists "anon_insert_calculo_dietetico" on public.paciente_calculo_dietetico;
create policy "anon_insert_calculo_dietetico"
on public.paciente_calculo_dietetico
for insert
to anon
with check (true);

drop policy if exists "anon_update_calculo_dietetico" on public.paciente_calculo_dietetico;
create policy "anon_update_calculo_dietetico"
on public.paciente_calculo_dietetico
for update
to anon
using (true)
with check (true);

drop policy if exists "anon_delete_calculo_dietetico" on public.paciente_calculo_dietetico;
create policy "anon_delete_calculo_dietetico"
on public.paciente_calculo_dietetico
for delete
to anon
using (true);

drop policy if exists "anon_select_checkins" on public.paciente_checkins;
create policy "anon_select_checkins"
on public.paciente_checkins
for select
to anon
using (true);

drop policy if exists "anon_insert_checkins" on public.paciente_checkins;
create policy "anon_insert_checkins"
on public.paciente_checkins
for insert
to anon
with check (true);

drop policy if exists "anon_update_checkins" on public.paciente_checkins;
create policy "anon_update_checkins"
on public.paciente_checkins
for update
to anon
using (true)
with check (true);

drop policy if exists "anon_delete_checkins" on public.paciente_checkins;
create policy "anon_delete_checkins"
on public.paciente_checkins
for delete
to anon
using (true);

drop policy if exists "anon_select_agenda" on public.agenda_recordatorios;
create policy "anon_select_agenda"
on public.agenda_recordatorios
for select
to anon
using (true);

drop policy if exists "anon_insert_agenda" on public.agenda_recordatorios;
create policy "anon_insert_agenda"
on public.agenda_recordatorios
for insert
to anon
with check (true);

drop policy if exists "anon_update_agenda" on public.agenda_recordatorios;
create policy "anon_update_agenda"
on public.agenda_recordatorios
for update
to anon
using (true)
with check (true);

drop policy if exists "anon_delete_agenda" on public.agenda_recordatorios;
create policy "anon_delete_agenda"
on public.agenda_recordatorios
for delete
to anon
using (true);
